Das folgende ist eine vereinfachte Liste - "Händlerin" ist leichter verständlich als "Kauffrau für interplanetaren Resourcen-Im- und Export"

= Pilot

Wähle 2 Spezialisierungen:

* Transporter (Raumschiff <=> Station)
* 1-2 Personen-Kampfflieger
* Große Schiffe (Kreuzer, Fregatten)
* Shuttle (Landung auf Planeten)
* Bodenfahrzeuge (Autos, LKW, Motorräder)
* Unterwasserfahrzeuge
* Flugzeuge (in Atmosphäre)
* Spezial Fahr- und Flugzeuge (Panzer, Hubschrauber, Raketenanzüge, Antigrav-Platformen)

Unterspezialisierungen auf bestimmte Modelle können einen zusätzlichen Bonus bringen. 


= Wissenschaftler

Verfügt über theoretisches Wissen zum jeweiligen Fachgebiet und kann Expertensysteme dazu bedienen.

Fachrichtungen (bis zu 2 auswählen für einen neuen Charakter)

- Xenoanthropologie (Humanoidologie :) ) - es wurden Überreste vieler humanoider Rassen gefunden. Ein komplett neues Forschungsgebiet!
- Biologie
-- Sauerstoffversorgung (komplexe Hydroponik, vgl. die Sauerstofferzeugung in The Expanse)
-- Xeno-Flora (stets inkl. irdischer Flora zum Vergleich)
-- Xeno-Fauna
- Chemie
-- Betriebsstoffe (vom weltraumtauglichen Schmieröl bis zum Synth-Kaffee)
-- Analyse von Stoffen
- Physik
-- Raketenwissenschaft (Antriebssysteme, Ballistik)
-- Lasertechnik
-- link:Raumflugmechanik[https://de.wikipedia.org/wiki/Raumflugmechanik]
- FTL-Theorie und Hyperraumantriebe (FTL = Faster Than Light = Überlichtreisen)
- Stellare und lokale Astronomie
- Linguistik
- Nanotechnologie
- Robotik
- Xeno-Informatik - die Verheerung spuckt fremdartige Wracks aus, deren IT-Systeme von massiven Energieströmen zerstört werden. Aber manchmal finden Forscher auch funktionsfähige Prozessoren mit noch identifizierbarer Software. Von der Auswertung versprechen sich manche Wissenschaftler neue Erkenntnisse über Antriebstechnik, Scanner, Waffensysteme, Kraftfelder und Robotersteuerungen. Vielleicht sogar eines Tage echte künstliche Intelligenzen?

= Mediziner 

Wähle 3

- Allgemeinmedizin ("normale" Krankheiten und Probleme)
- Erste Hilfe: Weltraum-Unfälle (Dekompression, Verstrahlung, Sauerstoffmangel - Überleben sichern, bis Patient bei der Medistation ankommt)
- Krankheiten: außerirdische (Mondstaubasbestose)
- Bedienung der Medistation (Chirurgie, Regenerationstank)
- Parasiten (Alien im Bauch)
- Geisteskrankheiten (Agoraphobie? Wieso, im All ist doch gar nichts, nur unendliche Weiten... oh.)
- Schutzprotokolle für Raumfahrer (Raumanzug gegen Reaktorstrahlung? Nebel aus Nanomaschinen vs FFP4-Masken? Reicht Alkohol, um Ewok-Läuse abzutöten?)

= Händlerin 

Wähle 3

- Schätzen (mit deinem kommerziellen Hintergrund kannst du den ungefähren Wert einer Sache bestimmen)
- Feilschen (wie auf dem Basar)
- Verhandeln (damit kannst du intergalaktische Handy-Verträge aushandeln)
- Kalkulation (Budgetplanung, Reichweite von Treibstoff + Sauerstoffvorrat + Lebensmitteln + Verbrauchsmaterial bei Expeditionen etc) 
- Händler-Wissen: exotisch; wähle 2 Unterskills
-- Nahrungsmittel
-- Metalle und seltene Erden
-- Gifte
-- Kunst
-- Stoffe und Kleidung (Alien-Seidenschlüpfer erzielen Höchstpreise, auch wenn kaum jemand die vier nötigen Beine hat, um sie zu tragen)

==== Kämpfer

Wähle 2 Spezialisierungen, dazu kommt der Skill: Schußwaffen (professionell): 3W6 auf Treffer 

- Sicherheit auf Station (Personenschutz, Kenntnis von Sicherheitsprotokollen)
- Abwehr von Kaperversuchen
- Bedienung von Gefechtscomputern (Schiff-zu-Schiff Kampf)
- Roboterkampf - "eigentlich" können Kampfroboter nicht durchdrehen...
- Kampf mit Powerarmor
- 0-G Nahkampf 
- Große Waffen (Raketenwerfer, Flak, Maschinengewehr und schwere Bolter)

==== Technikerin

Bedienung von komplexen Geräten (Drohnen, Schutzschirme, Laderoboter...)

==== Mechaniker 

Reparatur und Wartung von Geräten

==== Programmierer

Hacken & Softwareentwicklung mit/ohne KI-Unterstützung; Spezialisierung: Firmware, Cryptographie, KI

==== Verwerter (Scavenger) 

Durch die Verheerung entstandener Beruf: Abwracken und Plündern von Wracks, wertige Komponenten identifiziern und ausbauen.
