= Erforscher der Verheerung

Ein einfaches Science Fiction Rollenspiel.

= Szenario

Einige Jahrhunderte in der Zukunft: Die Menschheit hat sich Dank der Entdeckung des Überlichtantriebs in der Galaxie ausgebreitet und erste Hinweise auf außerirdische Zivilisationen gefunden (TODO: 1st/2nd contact?).

Vor 20 Jahren wurde die Verheerung (The Cataclysm) entdeckt - ein neues Wurmloch im unbewohnten Sternensystem DEVA-S209-K, das unentwegt Wracks von Raumschiffen aller Art ausspuckt und in chaotische Umlaufbahnen stößt. Die Schiffe sind nicht irdischen Ursprungs, sondern scheinen von einer Unzahl humanoider Rassen gebaut worden zu sein. Bisher wurden keine Überlebenden gefunden, und die Zerstörung hat fast immer extreme Ausmaße.

Am Rand des Systems wurden in großer Eile eine Zahl an Raumstationen gebaut, und große Recycler-Stationen nahmen ihre Arbeit auf, um die Schiffe zu verwerten, die aus dem gefährlichen inneren Ring herausdriften.  

Die Spieler sind Erforscher / Abenteurer in diesem System und versuchen, zusammen mit zehntausenden anderen ihr Glück zu versuchen. 
Ruhm, Reichtum und die Geheimnisse der Verheerung erwarten sie ... 

= Regeln

== Würfelsystem

W6-basiert.

Beispiel: Standardangriff: 3w6, Treffer gegen menschlichen Gegner ohne Rüstung bei 8.

Proben auf Attribute und Skills erfolgen ebenfalls über 3W6. Skills aus dem gewählten Beruf bekommen 3W6 und ermöglichen erschwerte Proben ohne zusätzliche Abzüge.

== Charaktererstellung

Im Moment ist die Start-Rasse Mensch. Grundwert für alle Attribute ist 10. Bonuspunkte zur Verteilung beim Erstellen eines Charakters: 10. Ein Attribut kann um bis zu 4 Punkte gesenkt werden, um ein anderes zu erhöhen.

=== Attribute

* Charisma
* Geschicklichkeit
* Intelligenz
* Konstitution
* Schnelligkeit
* Stärke
* Wahrnehmung
* Willenskraft

=== Berufe (Klassen)

Die Charaktere verfügen über die Standard-Grundausbildung für Raumfahrer (entsprechend einem Grundstudium). Sie können also mit Unterstützung der nicht-autonomen Künstlichen Intelligenz an Bord eines normalen Raumschiffes die alltäglichen Arbeiten zu Betrieb und Wartung übernehmen. Das ist z.B. Luftfilter wechseln, ein kleines Leck mit einem Notflicken abdichten oder eine Funkverbindung herstellen. Für ungewöhnliche Situationen sind aber stets Experten erforderlich. Die KI kann unterstützen, aber das Ergebnis ist (spieltechnisch betrachtet) dann nur Mittelmaß.

Skills und Fähigkeiten, die aus Berufen stammen, haben einen Basiswert von 3W6 für Proben und ermöglichen Proben für schwierige Situationen ohne Extraabzüge (gegenüber Amateuren, die nur 2W6 für Skills von fremden Berufen erhalten).

link:berufe.adoc[Liste der Berufe]

=== Skills

(Ohne Anspruch auf Vollständigkeit - weitere Vorschläge willkommen)

Neue Charaktere wählen n Skills aus. 

Du kannst auch Skills von anderen Berufen wählen, aber diese haben dann "Einsteiger/Amateur"-Level und bekommen nur 2W6 auf alle Proben. 

* 0-G Training (Kann komplexe Aktionen in Schwerelosigkeit durchführen ohne die Übersicht zu verlieren, erlaubt einem Mediziner z.B. die Wundversorgung ohne daß die Bandagen in einem Moment der Unachtsamkeit davonfliegen, während er den Patienten stabilisiert)
* Feilschen
* Überreden
* Etikette: das Wissen um die Grundregeln und das Verhalten in einer bestimmten gesellschaftlichen Gruppe
** Konzerne / Wirtschaft
** Wissenschaft
** Scavenger - z.B. daß man kein Wrack ausbeutet, daß schon ein anderer in diesem Moment in Arbeit hat.
** Unterwelt
* Wissen (Lore) - im Unterschied zu Etikette geht es nicht um das Verhalten, sondern mehr um Strukturen, Organisationen, Geschichte, Namen und Orte:
** Verheerung
** Galaktische Föderation
** Weltraumpiraten, Schmuggler (Überlappt mit Etikette: Unterwelt)
** Religionen
** Waffensysteme und Schutzschilde
** Außerirdische Lebensformen (Flora und Fauna von bisher gefundenen Planeten in der Galaxis)
** Roboter
** Große Maschinen (Recycler, die ein ganzes Schiff automatisch auseinandernehmen; Asteroiden-Bergbaumaschinen)
** Technik
** Chemie
** Physik
* Kampf (für Nicht-Kampfberufe)
** Nahkampf
** Schußwaffen
** Historische Waffen (Schwerter, Bogen... - wähle eine Unterspezialisierung)
* Suchen (z.B. versteckte Waffensysteme oder einen Safe)
* Feilschen
* Schwimmen
* Singen
* Brauen (Bier aus Algen, Gen-Gerste und Venushefe? Lecker!)
* Brennen (hochprozentigen Alkohol)
* Klettern
