= Erforscher der Verheerung

Ein einfaches Science Fiction Rollenspiel, basierend auf einer unveröffentlichten Geschichte :)

= Szenario

Einige Jahrhunderte in der Zukunft: Die Menschheit hat sich Dank der Entdeckung des Überlichtantriebs in der Galaxie ausgebreitet und erste Hinweise auf außerirdische Zivilisationen gefunden (TODO: definieren, evtl. schon 2nd contact).

Vor 20 Jahren wurde die Verheerung (The Cataclysm) entdeckt - ein neues Wurmloch im unbewohnten Sternensystem DEVA-S209-K, das unentwegt Wracks von Raumschiffen aller Art ausspuckt und in chaotische Umlaufbahnen stößt. Die Schiffe sind nicht irdischen Ursprungs, sondern scheinen von einer Unzahl humanoider Rassen gebaut worden zu sein. Die Spieler sind Erforscher / Abenteurer in diesem System und versuchen, zusammen mit zehntausenden anderen ihr Glück, Ruhm, Reichtum und die Geheimnisse der Verheerung erreichen. 

= Regeln

== Würfelsystem

W6-basiert.

Beispiel: Standardangriff: 3w6, Treffer gegen menschlichen Gegner ohne Rüstung bei 8.

Proben auf Attribute und Skills erfolgen ebenfalls über 3W6. Skills aus dem gewählten Beruf bekommen 3W6 und ermöglichen erschwerte Proben ohne zusätzliche Abzüge.

== Charaktererstellung

Im Moment ist die Start-Rasse Mensch. Grundwert für alle Attribute ist 10. Bonuspunkte zur Verteilung beim Erstellen eines Charakters: 10. Ein Attribut kann um bis zu 4 Punkte gesenkt werden, um ein anderes zu erhöhen.

=== Attribute

* Charisma
* Geschicklichkeit
* Intelligenz
* Konstitution
* Schnelligkeit
* Stärke
* Wahrnehmung
* Willenskraft

=== Berufe (Klassen)

Die Charaktere verfügen über die Standard-Grundausbildung für Raumfahrer (entsprechend einem Grundstudium). Sie können also mit Unterstützung der nicht-autonomen Künstlichen Intelligenz an Bord eines normalen Raumschiffes die alltäglichen Arbeiten zu Betrieb und Wartung übernehmen. Das ist z.B. Luftfilter wechseln, ein kleines Leck mit einem Notflicken abdichten oder eine Funkverbindung herstellen. Für ungewöhnliche Situationen sind aber stets Experten erforderlich. Die KI kann unterstützen, aber das Ergebnis ist (spieltechnisch betrachtet) dann nur Mittelmaß.

Skills und Fähigkeiten, die aus Berufen stammen, haben einen Basiswert von 3W6 für Proben und ermöglichen Proben für schwierige Situationen ohne Extraabzüge (gegenüber Amateuren, die nur 2W6 für Skills von fremden Berufen erhalten).

link:berufe.adoc[Liste der Berufe]

=== Skills

(Ohne Anspruch auf Vollständigkeit - weitere Vorschläge willkommen)

Neue Charaktere wählen n Skills aus. 

Du kannst auch Skills von anderen Berufen wählen, aber diese haben dann "Einsteiger/Amateur"-Level und bekommen nur 2W6 auf alle Proben. 

* 0-G Training (Kann komplexe Aktionen in Schwerelosigkeit durchführen ohne die Übersicht zu verlieren, erlaubt einem Mediziner z.B. die Wundversorgung ohne daß die Bandagen in einem Moment der Unachtsamkeit davonfliegen, während er den Patienten stabilisiert)
* Feilschen
* Überreden
* Etikette: Militär
* Etikette: Konzern / Wirtschaft
* Etikette: Wissenschaft
* Etikette: Scavenger
* Lore: Verheerung
* Lore: Galaktische Föderation
* Lore: Weltraumpiraten
* Nahkampf (für Nicht-Kampfberufe): 2W6-1 auf Treffer
* Schußwaffen (für Nicht-Kampfberufe): 2W6-1 auf Treffer
