= Erforscher der Verheerung

Ein einfaches Science Fiction Rollenspiel.

= Szenario

Einige Jahrhunderte in der Zukunft: Die Menschheit hat sich Dank der Entdeckung des Überlichtantriebs in der Galaxie ausgebreitet und erste Hinweise auf außerirdische Zivilisationen gefunden (TODO: 1st/2nd contact?).

Vor 20 Jahren wurde die Verheerung (The Cataclysm) entdeckt - ein neues Wurmloch im unbewohnten Sternensystem DEVA-S209-K, das unentwegt Wracks von Raumschiffen aller Art ausspuckt und in chaotische Umlaufbahnen stößt. Die Schiffe sind nicht irdischen Ursprungs, sondern scheinen von einer Unzahl humanoider Rassen gebaut worden zu sein. Bisher wurden keine Überlebenden gefunden, und die Zerstörung hat fast immer extreme Ausmaße.

Am Rand des Systems wurden in großer Eile eine Zahl an Raumstationen gebaut, und große Recycler-Stationen nahmen ihre Arbeit auf, um die Schiffe zu verwerten, die aus dem gefährlichen inneren Ring herausdriften.  

Die Spieler sind Erforscher / Abenteurer in diesem System und versuchen, zusammen mit zehntausenden anderen ihr Glück zu versuchen. 
Ruhm, Reichtum und die Geheimnisse der Verheerung erwarten sie ... 

= Regeln

== Würfelsystem

W6-basiert.

Beispiel: Standardangriff: 3w6, Treffer gegen menschlichen Gegner ohne Rüstung bei 8.

Proben auf Attribute: Attribut + 3W6 +- Modifikator(Schwierigkeit), Ergebnis muß bei >20 oder höher liegen.

Proben auf Skills: Basis 3W6 + Level +- Modifikator(Schwierigkeit), Ergebnis muß bei >11 liegen.

(mögliche Erweiterung: Skill-Level)

== Charaktererstellung

Im Moment ist die Start-Rasse Mensch. Grundwert für alle Attribute ist 10. Bonuspunkte zur Verteilung beim Erstellen eines Charakters: 10. Ein Attribut kann um bis zu 4 Punkte gesenkt werden, um ein anderes zu erhöhen.

=== Attribute

* Charisma
* Geschicklichkeit
* Intelligenz
* Konstitution
* Schnelligkeit
* Stärke
* Wahrnehmung
* Willenskraft

* Lebenspunkte: 3W6 + Konstitution

(mögliche Erweiterung: Chi / Mana / Psi-Kraft)
(TODO: Bonus auf Skillwürfe durch hohe Attribute)

=== Berufe (Klassen)

Die Charaktere verfügen über die Standard-Grundausbildung für Raumfahrer (entsprechend einem Grundstudium). Sie können also mit Unterstützung der nicht-autonomen Künstlichen Intelligenz an Bord eines normalen Raumschiffes die alltäglichen Arbeiten zu Betrieb und Wartung übernehmen. Das ist z.B. Luftfilter wechseln, ein kleines Leck mit einem Notflicken abdichten oder eine Funkverbindung herstellen. Für ungewöhnliche Situationen sind aber stets Experten erforderlich. Die KI kann unterstützen, aber das Ergebnis ist (spieltechnisch betrachtet) dann nur Mittelmaß.

Skills und Fähigkeiten, die aus Berufen stammen, haben einen Basiswert von 3W6 für Proben und ermöglichen Proben für schwierige Situationen ohne Extraabzüge (gegenüber Amateuren, die nur 2W6 für Skills von fremden Berufen erhalten).

include::berufe.adoc[leveloffset+2]

include::skills.adoc[leveloffset+2]


=== Implantate

Implantate ermöglichen transhumane Eigenschaften. Generell gibt es Implantate für alle Körperteile (nicht-genitaler Art ... - keine Hentaitentakel bitte).
Je nach Qualität können die zugehörigen Attribute einen Bonus erhalten oder einfach neue Fähigkeiten hinzugefügt werden (ein wenig wie in Cyberpunk).

Implantate können aus High-Tech Materialien oder aus biologischen Komponenten bestehen (diese sind deutlich teurer).

Neue Charaktere dürfen 1 Implantat normaler Qualität auswählen, weitere können später gekauft werden.

Beispiele:

* erweiterter Herzschrittmacher (inkl. Schutz vor Stromschlägen, beliebt bei Mechanikern...)
* Blutfilter (Gifte wie Alkohol können ausgefiltert oder abgebaut werden)
* Hormonregler und Medikamentenspender (z.B. automatischer Adrenalinschub für Stress- und Kampfsituationen, bzw. dämpfende Medikamente gegen Panikattacken wenn der Charakter unter Zeitdruck den Sauerstoffvorrat anschließen muß).
* Kommunikationsimplantat (kleiner Chip im Ohr/Kopf, um über Funk mit dem Bordsystem und der Mannschaft zu reden. Alternative sind normale Helm-Mikrophone und die Sprechanlagen an Bord)
* Bio-CPU: ein Computer im Kopf, erlaubt die direkte Kommunikation mit Computersystemen ("Wifi für's Hirn").
* Kraftverstärker: synthetische Muskeln bzw. optimieret Muskelsysteme für einen direkten Bonus zu Stärke (normale Qualität: +2)
* Optik: Cyberauge - endlich (aus-)sehen wie der Terminator!
* Waffenimplantate
** Laser
** Miniraketenwerfer
** Klingen (Spacewolverine)
* andere Organe (Lungensystem: ersetzt einen Teil der Lunge; Ohren: Geräuschsensoren ... "Der CPU-Lüfter läuft schon wieder unrund")
* Kampfaugmentierung: (normal: +1) Bonus auf Treffer, Schaden, Reaktion
* Schutzimplantate (Metallschädel, Knochenverstärker): reduzieren oder verhindern Schaden. (Normale Qualität: -2 Schadenspunkte bei mechanischer Einwirkung wie Stich-, Hieb- und Schnittverletzungen)

=== Vor- und Nachteile / Hintergrundgeschichte

Du kannst für deinen Charakter Vor- und Nachteile auswählen, um ihr oder ihm (oder $korrektesPronomen) mehr Tiefe zu verleihen. Um Powergaming zu vermeiden, sollten sich diese mehr oder weniger ausgleichen.

Beispiele:

==== Vorteile

- Kontakte (z.B. kennt vertrauenswürdige Händler, Mechaniker, CEOs oder Politiker auf einer Raumstation - oder hatte schon Berührung mit Schmugglern)
- Reichtum (hat ein reparaturbedürftiges Schiff in einem Raumhafen liegen, daß ein reicher Onkel hinterlassen / geschenkt hat)
- Begabungen (Eltern haben eine teure embrionale Gentherapie bezahlt: +x auf Intelligenz oder Stärke)
- Spezielle Ausbildung an Eliteuniversität (z.B. Wissenschaftler mit 3 Fachgebieten oder allgemein +1 Berufsskills )
- zusätzliches Implantat 
- ...

==== Nachteile

- Auf der Flucht vor Konsequenzen (in einem anderen System falsch oder zurecht eines Verbrechens angeklagt)
- Besondere Schwäche (Attribut mit -2 durch nicht verheilte Verletzung; "ungeschickt" = -2 auf Geschicklichkeit)
- defektes Implantat (kein Geld, um die Hormonsteuerung zu reparieren: Wutanfälle statt innerer Ruhe bei Stress)
- schlechter Ruf (berechtigt? Evtl. durch die Familie oder den Konzern, wo der Charakter gearbeitet hat)
- Schulden (mehr oder weniger rabiate Gläubiger)
- ...


== Welt

TODO

=== Roboter

=== Sec-Units

Inspiriert von Martha Wells' Murderbot Chronicles: Androiden, die ein biologisches Gehirn mit einem leistungsfähigen Elektronengehirn verbinden - und einem Kontrollchip, der sicherstellen soll, daß sie auf keinen Fall zu Mörderbots werden. Diese Bots werden bei Außeneinsätzen auf fremden Planeten oder bei diplomatischen Missionen zu potenziell aggressiven Parteien verwendet. Sie gelten offiziell als Sachen, nicht als Personen. Arbeiten Anweisungen selbständig ab, dürfen sich nicht zu weit vom Besitzer entfernen.

=== Combat-Units

Sec-units mit schweren Waffen, werden zur Sicherung kritischer Infrastruktur oder für krigerische Auseinandersetzungen verwendet.
